### PR TITLE
Implement convenience constructors for common projections

### PR DESCRIPTION
**Pull request by asinghvi17**
Implemented so far:
`WGS84, Mercator, TransverseMercator, UTM, AlbersEqualArea, Robinson, WinkelTripel`

### CODE REVIEW

**Comment by visr** [comment]
Thanks! My main concern is that this wraps the old PROJ 4 API, which will be deprecated. Best to build on the new one.

**Comment by asinghvi17** [comment]
Oh, `Projection` is being deprecated too?  Thought it was just the C API...will see what I can do to change it.

**Comment by visr** [comment]
Yeah I meant the C API. But Projection is now built on top of the C API that will be deprecated. Though perhaps we can switch out the implementation of Projection instead.

**Comment by asinghvi17** [comment]
Yeah I'd rather do that, since it's a pretty convenient thing to have - should be simple enough to do with the new API.

**Comment by asinghvi17** [comment]
https://proj.org/development/reference/functions.html?highlight=conversion#coordinate-transformation

This describes the C API for conversion between CRS.

**Comment by asinghvi17** [comment]
https://proj.org/development/reference/functions.html?highlight=conversion#coordinate-transformation

This describes the C API for conversion between CRS.

**Comment by asinghvi17** [comment]
Issues that still remain with this PR are:
- [ ] No real system to specify the datum / ellipsoid
- [ ] Moving to the Proj 6 API

I might just close this, and create a separate PR which transitions to the Proj 6 API first.

**Comment by visr** [comment]
I'll just close this, since it is targeting an API that is about to be removed.

I'm all for making it more convenient to construct projections, though I also worry about the maintenance burden of going down the route proposed here. E.g. which ones are important enough to get their own function? There are so many. A good start would be better documentation, and links to PROJ documentation like https://proj.org/operations/projections/index.html.

**Pull request closed without merging**
