### PR TITLE
switch to new Proj 5.2.0 build

### LINKED ISSUE #21: Building Proj4 on Windows fails due to linking issues
If I try to build Proj4 on Windows it fails with the following error, but it works if I run it as administrator:

┌ Error: Error building `Proj4`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
│ └ @ Base.Filesystem file.jl:789
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/JuliaGeo/PROJBuilder/releases/download/v4.9.3-3/PROJ.v4.9.3.x86_64-w64-mingw32.tar.gz to C:\Users\user\.julia\packag
es\Proj4\GICw3\deps\usr\downloads\PROJ.v4.9.3.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: Could not unpack C:\Users\user\.julia\packages\Proj4\GICw3\deps\usr\downloads\PROJ.v4.9.3.x86_64-w64-mingw32.tar.gz into C:\Users\user
\.julia\packages\Proj4\GICw3\deps\usr
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #unpack#98(::Bool, ::Function, ::String, ::String) at C:\Users\user\.julia\packages\BinaryProvider\4F5Hq\src\PlatformEngines.jl:660
│  [3] #unpack at .\none:0 [inlined]
│  [4] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at C:\Users\user\.julia\packages\BinaryProvider\4F5Hq\src\Pre
fix.jl:347
│  [5] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::St
ring) at .\none:0
│  [6] top-level scope at C:\Users\user\.julia\packages\Proj4\GICw3\deps\build.jl:43
│  [7] include at .\boot.jl:317 [inlined]
│  [8] include_relative(::Module, ::String) at .\loading.jl:1044
│  [9] include(::Module, ::String) at .\sysimg.jl:29
│  [10] include(::String) at .\client.jl:392
│  [11] top-level scope at none:0
│ in expression starting at C:\Users\user\.julia\packages\Proj4\GICw3\deps\build.jl:39
│
│ 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
│
│
│ Extracting archive:
│ ERROR: Can not create symbolic link : Access is denied. : C:\Users\user\.julia\packages\Proj4\GICw3\deps\usr\bin\invproj.exe
│ --
│ Path =
│ Type = tar
│ Code Page = UTF-8
│
│ ERROR: Can not create symbolic link : Access is denied. : C:\Users\user\.julia\packages\Proj4\GICw3\deps\usr\bin\invgeod.exe
│
│ Sub items Errors: 2
│
│ Archives with Errors: 1
│
│ Sub items Errors: 2
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

### PR DESCRIPTION
**Pull request by visr**
- update CI scripts
- regenerate projection codes

Should fix #21. @felixcremer, could you `add Proj4#newbuild` and test if this works for you without running it as administrator?

### CODE REVIEW

**Comment by felixcremer** [comment]
I will test it on Wednesday when I am back at the office.

**Comment by visr** [comment]
If everybody's ok I think I'll go ahead and merge and tag this. @felixcremer would still be good to know if this indeed fixes your issue, though that doesn't need to block merging this I think.

**Comment by felixcremer** [comment]
Thanks, this works now, but I get a warning, that Libdl is not in the dependency list of Proj4.

**Comment by visr** [comment]
Ok sounds good. The Libdl issue is this: https://github.com/bicycle1885/CodecZlib.jl/pull/26#issuecomment-411649990

So even though we don't use Libdl directly, the fix for now is to add `using Libdl`, which I just did.

**Pull request merged**
